/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecomendacoesRouteImport } from './routes/recomendacoes'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LigacoesRouteImport } from './routes/ligacoes'
import { Route as EsquentarRouteImport } from './routes/esquentar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogComoAplicarSpinSellingRouteImport } from './routes/blog.como-aplicar-spin-selling'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const RecomendacoesRoute = RecomendacoesRouteImport.update({
  id: '/recomendacoes',
  path: '/recomendacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LigacoesRoute = LigacoesRouteImport.update({
  id: '/ligacoes',
  path: '/ligacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EsquentarRoute = EsquentarRouteImport.update({
  id: '/esquentar',
  path: '/esquentar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComoAplicarSpinSellingRoute =
  BlogComoAplicarSpinSellingRouteImport.update({
    id: '/blog/como-aplicar-spin-selling',
    path: '/blog/como-aplicar-spin-selling',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/mcp': typeof McpRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/mcp': typeof McpRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/mcp': typeof McpRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/esquentar'
    | '/ligacoes'
    | '/mcp'
    | '/prospeccao'
    | '/recomendacoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/como-aplicar-spin-selling'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/esquentar'
    | '/ligacoes'
    | '/mcp'
    | '/prospeccao'
    | '/recomendacoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/como-aplicar-spin-selling'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/esquentar'
    | '/ligacoes'
    | '/mcp'
    | '/prospeccao'
    | '/recomendacoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/como-aplicar-spin-selling'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EsquentarRoute: typeof EsquentarRoute
  LigacoesRoute: typeof LigacoesRoute
  McpRoute: typeof McpRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  RecomendacoesRoute: typeof RecomendacoesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogComoAplicarSpinSellingRoute: typeof BlogComoAplicarSpinSellingRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recomendacoes': {
      id: '/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof RecomendacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligacoes': {
      id: '/ligacoes'
      path: '/ligacoes'
      fullPath: '/ligacoes'
      preLoaderRoute: typeof LigacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esquentar': {
      id: '/esquentar'
      path: '/esquentar'
      fullPath: '/esquentar'
      preLoaderRoute: typeof EsquentarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-aplicar-spin-selling': {
      id: '/blog/como-aplicar-spin-selling'
      path: '/blog/como-aplicar-spin-selling'
      fullPath: '/blog/como-aplicar-spin-selling'
      preLoaderRoute: typeof BlogComoAplicarSpinSellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EsquentarRoute: EsquentarRoute,
  LigacoesRoute: LigacoesRoute,
  McpRoute: McpRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  RecomendacoesRoute: RecomendacoesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogComoAplicarSpinSellingRoute: BlogComoAplicarSpinSellingRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
