/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecomendacoesRouteImport } from './routes/recomendacoes'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as LigacoesRouteImport } from './routes/ligacoes'
import { Route as EsquentarRouteImport } from './routes/esquentar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogComoAplicarSpinSellingRouteImport } from './routes/blog.como-aplicar-spin-selling'

const RecomendacoesRoute = RecomendacoesRouteImport.update({
  id: '/recomendacoes',
  path: '/recomendacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const LigacoesRoute = LigacoesRouteImport.update({
  id: '/ligacoes',
  path: '/ligacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EsquentarRoute = EsquentarRouteImport.update({
  id: '/esquentar',
  path: '/esquentar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComoAplicarSpinSellingRoute =
  BlogComoAplicarSpinSellingRouteImport.update({
    id: '/blog/como-aplicar-spin-selling',
    path: '/blog/como-aplicar-spin-selling',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/esquentar'
    | '/ligacoes'
    | '/prospeccao'
    | '/recomendacoes'
    | '/blog/como-aplicar-spin-selling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/esquentar'
    | '/ligacoes'
    | '/prospeccao'
    | '/recomendacoes'
    | '/blog/como-aplicar-spin-selling'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/esquentar'
    | '/ligacoes'
    | '/prospeccao'
    | '/recomendacoes'
    | '/blog/como-aplicar-spin-selling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EsquentarRoute: typeof EsquentarRoute
  LigacoesRoute: typeof LigacoesRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  RecomendacoesRoute: typeof RecomendacoesRoute
  BlogComoAplicarSpinSellingRoute: typeof BlogComoAplicarSpinSellingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recomendacoes': {
      id: '/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof RecomendacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligacoes': {
      id: '/ligacoes'
      path: '/ligacoes'
      fullPath: '/ligacoes'
      preLoaderRoute: typeof LigacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esquentar': {
      id: '/esquentar'
      path: '/esquentar'
      fullPath: '/esquentar'
      preLoaderRoute: typeof EsquentarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-aplicar-spin-selling': {
      id: '/blog/como-aplicar-spin-selling'
      path: '/blog/como-aplicar-spin-selling'
      fullPath: '/blog/como-aplicar-spin-selling'
      preLoaderRoute: typeof BlogComoAplicarSpinSellingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EsquentarRoute: EsquentarRoute,
  LigacoesRoute: LigacoesRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  RecomendacoesRoute: RecomendacoesRoute,
  BlogComoAplicarSpinSellingRoute: BlogComoAplicarSpinSellingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
