/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecomendacoesRouteImport } from './routes/recomendacoes'
import { Route as LigacoesRouteImport } from './routes/ligacoes'
import { Route as EsquentarRouteImport } from './routes/esquentar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogComoAplicarSpinSellingRouteImport } from './routes/blog.como-aplicar-spin-selling'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendacoesRoute = RecomendacoesRouteImport.update({
  id: '/recomendacoes',
  path: '/recomendacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LigacoesRoute = LigacoesRouteImport.update({
  id: '/ligacoes',
  path: '/ligacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EsquentarRoute = EsquentarRouteImport.update({
  id: '/esquentar',
  path: '/esquentar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComoAplicarSpinSellingRoute =
  BlogComoAplicarSpinSellingRouteImport.update({
    id: '/blog/como-aplicar-spin-selling',
    path: '/blog/como-aplicar-spin-selling',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/esquentar': typeof EsquentarRoute
  '/ligacoes': typeof LigacoesRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/como-aplicar-spin-selling': typeof BlogComoAplicarSpinSellingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esquentar'
    | '/ligacoes'
    | '/recomendacoes'
    | '/sitemap.xml'
    | '/blog/como-aplicar-spin-selling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esquentar'
    | '/ligacoes'
    | '/recomendacoes'
    | '/sitemap.xml'
    | '/blog/como-aplicar-spin-selling'
  id:
    | '__root__'
    | '/'
    | '/esquentar'
    | '/ligacoes'
    | '/recomendacoes'
    | '/sitemap.xml'
    | '/blog/como-aplicar-spin-selling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EsquentarRoute: typeof EsquentarRoute
  LigacoesRoute: typeof LigacoesRoute
  RecomendacoesRoute: typeof RecomendacoesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogComoAplicarSpinSellingRoute: typeof BlogComoAplicarSpinSellingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendacoes': {
      id: '/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof RecomendacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligacoes': {
      id: '/ligacoes'
      path: '/ligacoes'
      fullPath: '/ligacoes'
      preLoaderRoute: typeof LigacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esquentar': {
      id: '/esquentar'
      path: '/esquentar'
      fullPath: '/esquentar'
      preLoaderRoute: typeof EsquentarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-aplicar-spin-selling': {
      id: '/blog/como-aplicar-spin-selling'
      path: '/blog/como-aplicar-spin-selling'
      fullPath: '/blog/como-aplicar-spin-selling'
      preLoaderRoute: typeof BlogComoAplicarSpinSellingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EsquentarRoute: EsquentarRoute,
  LigacoesRoute: LigacoesRoute,
  RecomendacoesRoute: RecomendacoesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogComoAplicarSpinSellingRoute: BlogComoAplicarSpinSellingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
